package traefik_errors

import (
	"net/http"
)

// IsTraefikGeneratedError determines if a given error status code is likely
// to have been generated by Traefik itself rather than passed through from an upstream service.
func IsTraefikGeneratedError(statusCode int, backendAttempted bool) bool {
	// Error codes that are typically generated by Traefik:
	// - 404: No matching route (when no backend was attempted)
	// - 502: Bad Gateway (when backend is unreachable)
	// - 503: Service Unavailable (when no backend is available)
	// - 504: Gateway Timeout (when backend times out)
	
	switch statusCode {
	case http.StatusBadGateway, http.StatusServiceUnavailable, http.StatusGatewayTimeout:
		// These errors are almost always generated by Traefik when acting as a proxy
		return true
	case http.StatusNotFound:
		// For 404, we need to distinguish between:
		// - 404 from Traefik (no route found)
		// - 404 from backend (resource not found)
		return !backendAttempted
	default:
		// Other status codes are typically from backends
		return false
	}
}
