export enum MiddlewareType {
  AddPrefix = 'addPrefix',
  BasicAuth = 'basicAuth',
  Buffering = 'buffering',
  Chain = 'chain',
  CircuitBreaker = 'circuitBreaker',
  Compress = 'compress',
  ContentType = 'contentType',
  DigestAuth = 'digestAuth',
  Errors = 'errors',
  TraefikErrors = 'traefikErrors',
  ForwardAuth = 'forwardAuth',
  Headers = 'headers',
  IPAllowList = 'ipAllowList',
  InFlightReq = 'inFlightReq',
  PassTLSClientCert = 'passTLSClientCert',
  RateLimit = 'rateLimit',
  RedirectRegex = 'redirectRegex',
  RedirectScheme = 'redirectScheme',
  ReplacePath = 'replacePath',
  ReplacePathRegex = 'replacePathRegex',
  Retry = 'retry',
  StripPrefix = 'stripPrefix',
  StripPrefixRegex = 'stripPrefixRegex',
  Plugin = 'plugin'
}
